server:
  port: 8099

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bank-account-service
          uri: lb://bank-account-service
          predicates:
            - Path=/bank-account-service/**
          filters:
            - RewritePath=/bank-account-service/(?<x>.*), /$\{x}
        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/credit-service/**
          filters:
            - RewritePath=/credit-service/(?<x>.*), /$\{x}
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/**
          filters:
            - RewritePath=/customer-service/(?<x>.*), /$\{x}
        - id: movement-service
          uri: lb://movement-service
          predicates:
            - Path=/movement-service/**
          filters:
            - RewritePath=/movement-service/(?<x>.*), /$\{x}