server:
    port: 8082
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bankAccount

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

controller:
  bank-account:
    base-path: /bank-accounts
  checking-account:
    base-path: /checking
    method:
      register-personal: /personal
      register-business: /business
  fixed-term-account:
    base-path: /fixed-term
  savings-account:
    base-path: /savings
  method:
    getAll:
    getById: /{id}
    register:
    updateById: /{id}
    deleteById: /{id}
  path-variable:
    id: id

customer-service:
  base-url: http://localhost:8099/customers
  method:
    get-customer-by-id: /customers/{id}

credit-service:
  base-url: http://localhost:8099/credits
  method:
    get-credits-by-customer-id: /credits/customers/{customerId}