server:
    port: 8082
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bankAccount

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

customerService:
  baseUrl: http://localhost:8099/customer-service
  method:
    getCustomerById: /customers/{id}

creditService:
  baseUrl: http://localhost:8099/credit-service
  method:
    getCreditsByCustomerId: /credits/customers/{customerId}