server:
    port: 8083
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/credit

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

customerService:
  baseUrl: http://localhost:8099/customer-service
  method:
    getCustomerById: /customers/{id}

resilience4j.circuitbreaker:
    instances:
        customerService:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10

resilience4j.timelimiter:
    instances:
        customerService:
            timeoutDuration: 2s
            cancelRunningFuture: false
  