server:
    port: 8083
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/credit

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

controller:
  credit:
    base-path: /credits
  method:
    getAll:
    getById: /{id}
    register:
    updateById: /{id}
    deleteById: /{id}
  path-variable:
    id: id

customer-service:
  base-url: http://localhost:8099/customers
  method:
    get-customer-by-id: /customers/{id}
  