server:
    port: 8083
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/credit

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

controller:
  credit:
    basePath: /credits
    method:
      getByCustomerId: /customers/{customerId}
    pathVariable:
      customerId: customerId
  method:
    getAll:
    getById: /{id}
    register:
    updateById: /{id}
    deleteById: /{id}
  pathVariable:
    id: id

customerService:
  baseUrl: http://localhost:8099/customers
  method:
    getCustomerById: /customers/{id}
  