server:
    port: 8083
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/credit

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

customerService:
  baseUrl: http://localhost:8099/customer-service
  method:
    getCustomerById: /customers/{id}
  