server:
    port: 8081
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bankingBusiness

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}

bankAccountService:
  baseUrl: http://localhost:8099/bank-account-service
  method:
    getBankAccountsByCustomerId: /bank-accounts/customers/{customerId}

creditService:
  baseUrl: http://localhost:8099/credit-service
  method:
    getCreditsByCustomerId: /credits/customers/{customerId}

resilience4j.circuitbreaker:
  instances:
    creditService:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
    bankAccountService:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

resilience4j.timelimiter:
  instances:
    creditService:
      timeoutDuration: 2s
      cancelRunningFuture: false
    bankAccountService:
      timeoutDuration: 2s
      cancelRunningFuture: false