server:
    port: 8081
  
spring:
  data:
    mongodb:
      uri: mongodb+srv://pfsr98:gmCHvU2F66iYwts@cluster0.no81esn.mongodb.net/meseroapp?retryWrites=true&w=majority

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}