server:
    port: 8081
  
spring:
  data:
    mongodb:
      uri:  ${MONGODB_URI:mongodb://localhost:27017/customer}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}