server:
    port: 8081
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bankingBusiness

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}