server:
    port: 8081
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

controller:
  customer:
    base-path: /customers
  method:
    getAll:
    getById: /{id}
    register:
    updateById: /{id}
    deleteById: /{id}
  path-variable:
    id: id