server:
    port: 8081
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

controller:
  personal-customer:
    base-path: /personal
  business-customer:
    base-path: /business
  method:
    getAll:
    getById: /{${controller.method.path-variable.id}}
    register:
    updateById: /{${controller.method.path-variable.id}}
    deleteById: /{${controller.method.path-variable.id}}
  path-variable:
    id: id