server:
    port: 8084
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/movement

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

bankAccountService:
  base-url: http://localhost:8099/bank-account-service
  method:
    getBankAccountById: /bank-accounts/{id}
    getBankAccountsByCustomerId: /bank-accounts/customers/{customerId}
    updateBankAccountById: /bank-accounts/{id}

creditService:
  baseUrl: http://localhost:8099/credit-service
  method:
    getCreditById: /credits/{id}
    updateCreditById: /credits/{id}